### ISSUE TITLE
TOML Configuration File Support

### ISSUE THREAD

**Issue by Goldziher** [Goldziher/uncomment#17]
**Description:**
Add support for configuration files that allow users to customize uncomment behavior on a per-project basis.

**Configuration Features:**
- Project-specific preservation patterns
- Language-specific settings
- Default CLI options
- Custom file associations

**Config File Locations (in order of precedence):**
1. `.uncommentrc.toml` in current directory
2. `uncomment.toml` in current directory
3. `.uncommentrc.toml` in project root (git root)
4. `~/.config/uncomment/config.toml` (global)

**Example Configuration:**
```toml
# .uncommentrc.toml
[global]
remove_todos = false
remove_docs = false
preserve_patterns = ["HACK", "WORKAROUND"]

[languages.python]
preserve_patterns = ["mypy:", "type:", "noqa", "pragma:"]
remove_docs = true  # Override global setting

[languages.javascript]
preserve_patterns = ["@ts-expect-error", "webpack"]
extensions = [".mjs", ".cjs"]  # Additional extensions

[languages.custom]
name = "CustomLang"
extensions = [".custom"]
comment_nodes = ["comment"]
```

**Tasks:**
- [ ] Add `toml` and `serde` dependencies
- [ ] Create configuration structs
- [ ] Implement config file discovery logic
- [ ] Merge configurations with CLI arguments (CLI takes precedence)
- [ ] Add validation for configuration values
- [ ] Create `--init` command to generate config template
- [ ] Add `--config` flag to specify custom config path
- [ ] Update all language processors to use config
- [ ] Write comprehensive tests for config merging
- [ ] Document configuration options in README

**Implementation Notes:**
- Use `serde` for TOML deserialization
- Config should be loaded once and passed through context
- Invalid config should show helpful error messages
